name: ${project.name}
version: ${project.version}
description: ${project.description}
author: Kenny
main: me.kenny.emcdisguise.EMCDisguise
commands:
  disguise:
    aliases: [d, dis]
    description: Disguises you.
  undisguise:
    aliases: [undis]
    description: Undisguises you.